### ISSUE TITLE
Add new hooks

### ISSUE THREAD

**Issue by stevenpersia** [stevenpersia/captain-hook#1]
Feel free to add your best hooks 👍 

Add your js file and edit `README.md` file like other hooks.

**Comment by webbertakken** [comment]
@stevenpersia I added a hook, that will contain a followup if you're interested. See #5

**Comment by stevenpersia** [comment]
I merge your PR. Thank you @webbertakken !

**Comment by webbertakken** [comment]
@stevenpersia neat! Here's also #6 and #7 followup as promised. These hooks have been extensively tested on my side. 

Hope that more people will find this useful.

**Comment by benfluleck** [comment]
Hi @stevenpersia , your useFetch could do with a loading state to signal to the user when the fetch has started and when it finishes. Let me know if It is something I can extend 😄

**Comment by benfluleck** [comment]
Done https://github.com/stevenpersia/captain-hook/pull/8

**Comment by stevenpersia** [comment]
Nice improvement @benfluleck ! Thank you.

**Comment by stevenpersia** [comment]
@webbertakken, these hooks must be very useful. I just need `useFocusOutside` in my current side project. Thanks !

**Comment by mfaridzia** [comment]
@stevenpersia I added a hook, please see [#10](https://github.com/stevenpersia/captain-hook/pull/10)

Thanks

**Comment by stevenpersia** [comment]
Merged. Thank you @mfaridzia

**Comment by soub4i** [comment]
@stevenpersia I added a new one #11

**Comment by stevenpersia** [comment]
Merged. Thank you @AbderrahimSoubaiElidrissi !
