### ISSUE TITLE
useSlug and useSwap aren't custom hooks

### ISSUE THREAD

**Issue by stevenpetryk** [stevenpersia/captain-hook#17]
These two hooks don't call any other hooks, so I think it could confuse folks new to hooks that this repo categorizes them as hooks. These are just pure functions and they don't have to follow the [rules of hooks](https://reactjs.org/docs/hooks-rules.html).

**Comment by stevenpersia** [comment]
Yo @stevenpetryk !
Thank you for your participation. You are absolutely right, that's why I've removed them from repository. :+1:
